export DOC_ROOT=/home/will/DOC_ROOT
export ACE_ROOT=$DOC_ROOT/ACE
export TAO_ROOT=$DOC_ROOT/TAO
export CIAO_ROOT=$DOC_ROOT/CIAO
export DANCE_ROOT=$DOC_ROOT/DAnCE
export MPC_ROOT=$DOC_ROOT/MPC

export PATH=$ACE_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH

export NDDSHOME=/home/will/ndds.4.5d
export NDDSARCHITECTURE=i86Linux2.6gcc4.4.3
export LD_LIBRARY_PATH=$NDDSHOME/$NDDSARCHITECTURE:$LD_LIBRARY_PATH


export DDS_ROOT=/home/will/DOC_ROOT/DDS
export LD_LIBRARY_PATH=$DDS_ROOT/lib:$LD_LIBRARY_PATH
export PATH=$DDS_ROOT/bin:$PATH


#export ACM_ROOT=/home/will/ACM-1.0.2
