export ACM_ROOT=$PWD/ACM-I
export MBSHM_ROOT=$PWD/ACM-I
export ACM_SRC=$PWD/ACM-src
export ACE_ROOT=$PWD/DOC_ROOT/ACE
export MPC_ROOT=$PWD/DOC_ROOT/MPC/
export TAO_ROOT=$PWD/DOC_ROOT/TAO
export CIAO_ROOT=$PWD/DOC_ROOT/CIAO
export PATH=$PATH:$MBSHM_ROOT/bin:$ACE_ROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MBSHM_ROOT/lib:$ACE_ROOT/lib
export DDS_ROOT=$PWD/DOC_ROOT/DDS
export PATH=$PATH:$DDS_ROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DDS_ROOT/lib
export PKG_CONFIG_PATH=$MBSHM_ROOT/lib/pkgconfig/

